### Get all budgets
GET https://budget-service-xl8q.onrender.com/api/budgets
Accept: application/json

###

### Create a new budget
POST https://budget-service-xl8q.onrender.com/api/budgets
Content-Type: application/json

{
  "category": "Utilities",
  "limit": 150,
  "month": "2025-05"
}
